[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = [
  "pnpm config set strict-peer-dependencies false",
  "pnpm install --no-frozen-lockfile --shamefully-hoist"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
