[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm i --no-frozen-lockfile || pnpm i"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
